# 基础镜像
FROM nginx
# author
LABEL MAINTAINER="lw"

# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/pc /usr/share/nginx/html/pc
COPY ./html/mobile /usr/share/nginx/html/mobile
